feat: Implemented IConverterConfiguration.targetReplace.
mike-lischke/java2typescript pull request #5
Opened 2022-11-27 14:41 UTC by kibae

I tried modifying the targetReplace option to work.
If you feel that this is the intended behavior and fits the project's conventions, please merge.

2022-11-27 18:10 UTC, mike-lischke requested changes
That looks good to me. You just have to rebase on master first, to make it work.

2022-11-27 20:06 UTC, kibae commented
@mike-lischke I merged master branch :)

2022-11-28 04:43 UTC, kibae commented on src/conversion/FileProcessor.ts
> +                    let converted: string = String.fromCharCode(...builder.array());
@mike-lischke I changed this because java.lang.StringBuilder.toString() returns java.lang.String .

2022-11-28 07:46 UTC, mike-lischke approved these changes

2022-11-28 07:46 UTC, merged